# Generated by Django 3.2.9 on 2022-05-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter device name', max_length=60, verbose_name='Device name')),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lane_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 1')),
                ('enable_1', models.BooleanField(blank=True, default=False, verbose_name='Activate Lane 1')),
                ('lane_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 2')),
                ('enable_2', models.BooleanField(blank=True, default=False, verbose_name='Activate Lane 2')),
                ('lane_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 3')),
                ('enable_3', models.BooleanField(blank=True, default=False, verbose_name='Activate Lane 3')),
                ('lane_4', models.CharField(blank=True, max_length=20, null=True, verbose_name='lane 4')),
                ('enable_4', models.BooleanField(blank=True, default=False, verbose_name='Activate Lane 4')),
                ('lane_5', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 5')),
                ('enable_5', models.BooleanField(blank=True, default=False, verbose_name='Activate Lane 5')),
                ('lane_6', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 6')),
                ('enable_6', models.BooleanField(blank=True, default=False, verbose_name='Activate Lane 6')),
                ('lane_7', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 7')),
                ('enable_7', models.BooleanField(blank=True, default=False, verbose_name='Activate Lane 7')),
                ('lane_8', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 8')),
                ('enable_8', models.BooleanField(blank=True, default=False, verbose_name='Activate Lane 8')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('enable', models.BooleanField(blank=True, default=False, verbose_name='Activate')),
                ('remote_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ip adresss')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Release date')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_images', models.ImageField(blank=True, null=True, upload_to='static/assets/img')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
