# Generated by Django 3.2.9 on 2022-06-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20220612_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lane1_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 1 Name'),
        ),
        migrations.AddField(
            model_name='device',
            name='lane2_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 2 Name'),
        ),
        migrations.AddField(
            model_name='device',
            name='lane3_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 3 Name'),
        ),
        migrations.AddField(
            model_name='device',
            name='lane4_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 4 Name'),
        ),
        migrations.AddField(
            model_name='device',
            name='lane5_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 5 Name'),
        ),
        migrations.AddField(
            model_name='device',
            name='lane6_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 6 Name'),
        ),
        migrations.AddField(
            model_name='device',
            name='lane7_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 7 Name'),
        ),
        migrations.AddField(
            model_name='device',
            name='lane8_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lane 8 Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
